[package]
name = "vncdisplay"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
log = "0.4"
tokio = { version = "1", default-features = false, features = ["rt", "net", "macros", "io-util"] }
